### ISSUE TITLE
python_package_analyze/create output/input discrepancy

### ISSUE THREAD

**Issue by tjuedema** [cooperative-computing-lab/cctools#2350]
This could very well just be from incompatible versions of CCTools and conda-pack, but I'm getting the following:

```bash
(base) [tjuedema@crcfe01 test2]$ python_package_analyze tensor.py output.json
(base) [tjuedema@crcfe01 test2]$ python_package_create output.json env.tar.gz
Creating temporary environment in /tmp/tmptqjib18v

EnvironmentFileExtensionNotValid: '/scratch365/tjuedema/resnet/cctools/apps/wq_hypersweep/wq_test/test2/output.json' file extension must be one of '.txt', '.yaml' or '.yml'

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/t/tjuedema/miniconda3/bin/python_package_create", line 33, in <module>
    pack_env(args.spec, args.out)
  File "/afs/crc.nd.edu/user/t/tjuedema/miniconda3/bin/python_package_create", line 21, in pack_env
    '--file', spec])
  File "/afs/crc.nd.edu/user/t/tjuedema/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--prefix', '/tmp/tmptqjib18v', '--file', 'output.json']' returned non-zero exit status 1.
```

tensor.py just consists of this:

``` python
import tensorflow as tf
print(tf.__version__)
```

**Comment by trshaffer** [comment]
Conda is kind of picky about the spec format, it won't accept .json files. You need to change the extension to .yaml (JSON is a subset of YAML, so the file otherwise works). Maybe a doc update is needed?

**Comment by tjuedema** [comment]
Used .yaml and .yml as extensions and it works as intended. Using .txt isn't an option unless a a separate case is added.

```bash
(base) [tjuedema@crcfe01 wq_hypersweep]$ python_package_create output.txt env.tar.gz                                         Creating temporary environment in /tmp/tmpgghndpey

SpecNotFound: Environment with requirements.txt file needs a name

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/t/tjuedema/miniconda3/bin/python_package_create", line 33, in <module>
    pack_env(args.spec, args.out)
  File "/afs/crc.nd.edu/user/t/tjuedema/miniconda3/bin/python_package_create", line 21, in pack_env
    '--file', spec])
  File "/afs/crc.nd.edu/user/t/tjuedema/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--prefix', '/tmp/tmpgghndpey', '--file', 'output.txt']' returned non-zero exit status 1.
```

I agree a copy+replace of .json to .yaml would fix this. I'm just not sure if it's just a me problem in my environment, or if conda-pack was updated since this code was written and the tool should be updated as well.

**Comment by dthain** [comment]
What's the resolution on this -- is a doc update needed, or just close the issue?

**Comment by tjuedema** [comment]
I spun up an AWS E2C instance to get a clean environment to install cctools and check the scripts. Setup looked like this:
```bash
sudo yum update
sudo yum install python38
sudo amazon-linux-extras install python3.8
wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
sh Anaconda3-2020.02-Linux-x86_64.sh
source ~/.bashrc
conda install -y -c conda-forge ndcctools
conda install -c conda-forge conda-pack
```

Using the commands in the readme generates the same error as before:
```bash
python_package_analyze python.py dependencies.yaml
python_package_create dependencies.yaml example_venv.tar.gz

Creating temporary environment in /tmp/tmpvj1gdeak

EnvironmentFileExtensionNotValid: '/home/ec2-user/dependencies.json' file extension must be one of '.txt', '.yaml' or '.yml'

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/bin/python_package_create", line 33, in <module>
    pack_env(args.spec, args.out)
  File "/home/ec2-user/anaconda3/bin/python_package_create", line 21, in pack_env
    '--file', spec])
  File "/home/ec2-user/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--prefix', '/tmp/tmpvj1gdeak', '--file', 'dependencies.json']' returned non-zero exit status 1.
```


Running this command set executes just fine:
```bash
python_package_analyze python.py dependencies.yaml
python_package_create dependencies.yaml example_venv.tar.gz
python_package_run --environment example_venv.tar.gz python3 python.py 
```

So it seems to me that a doc update is in order, I'll submit a PR to update the readme and commandline option descriptions in the scripts.

Also, I noticed that conda-pack isn't installed as a dependency of cctools when you do:

```bash
conda install -y -c conda-forge ndcctools
```

It might be worth including conda-pack to the dependency list so these scripts are immediately usable after installing cctools.

**Comment by dthain** [comment]
@btovar can you check/update the dependencies for our conda package?

**Comment by btovar** [comment]
On it.

**Comment by btovar** [comment]
Fixed by using yaml instead of json.
