### ISSUE TITLE
DaskVine: Recursion Error

### ISSUE THREAD

**Issue by dthain** [cooperative-computing-lab/cctools#3393]
Dask+TaskVine when used on some simple array examples crashes with an infinite recursion error in `taskvine/dask_dag.py`:

Setup as follows:

```
conda create -n daskvine -c conda-forge dask ndcctools
conda activate daskvine
python vine-dask-test.py & vine_worker localhost 9123 &
```

Where vine-dask-test.py is:

```
import ndcctools.taskvine as vine
import dask
import dask.array as da

# Create a new manager listening on port 9123                                                
manager = vine.DaskVine(9123)

# Define the dask workflow...                                                                
x = da.random.random((1000,1000),chunks=500)
y = x + x.T
z = y[::2,500:].mean(axis=1)

result = z.compute(scheduler=manager.get)

print(result);
```

It executes several tasks on the worker, and then crashes in `y = x + x.T` with the following:

```
Traceback (most recent call last):
  File "/tmp/cctools-packaging-test/vine-dask-test.py", line 15, in <module>
    result = z.compute(scheduler=manager.get)
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_executor.py", line 109, in get
    raise e
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_executor.py", line 106, in get
    return self._dask_execute(dsk, keys)
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_executor.py", line 131, in _dask_execute
    rs = dag.set_result(t.key, DaskVineFile(t.output_file, t.key, self.staging_directory))
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 157, in set_result
    rs.extend(self.set_result(key, self.get_result(sexpr)))  # case e.g, "x": "y", and we just set the value of "y"
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 157, in set_result
    rs.extend(self.set_result(key, self.get_result(sexpr)))  # case e.g, "x": "y", and we just set the value of "y"
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 157, in set_result
    rs.extend(self.set_result(key, self.get_result(sexpr)))  # case e.g, "x": "y", and we just set the value of "y"
  [Previous line repeated 988 more times]
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 156, in set_result
    if self.graph_keyp(sexpr):
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 96, in graph_keyp
    if DaskVineDag.keyp(s):
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 39, in keyp
    return DaskVineDag.hashable(s) and not DaskVineDag.taskp(s)
  File "/tmp/daskvine/lib/python3.10/site-packages/ndcctools/taskvine/dask_dag.py", line 56, in hashable
    hash(s)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by dthain** [comment]
I think the way to proceed here is to simplify this example to a smaller trivial array, then generate the dask graph in text form to figure out what is objectionable.

**Comment by dthain** [comment]
Fixed, thanks!
