### ISSUE TITLE
vine: vine_plot_txn_log failed to parse library task

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3571]
I ran a function call example and tried to use `vine_plot_txn_log` to plot the performance, it failed with the error message:

```shell
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/j/jzhou24/scripts/vine_plot_txn_log.py", line 861, in <module>
    p = ParseTxn(args.log, args.expand_waiting, args.tasks_range)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/scripts/vine_plot_txn_log.py", line 174, in __init__
    self._parse()
  File "/afs/crc.nd.edu/user/j/jzhou24/scripts/vine_plot_txn_log.py", line 399, in _parse
    self._parse_task(time, manager_pid, target, event, arg)
  File "/afs/crc.nd.edu/user/j/jzhou24/scripts/vine_plot_txn_log.py", line 347, in _parse_task
    la = self.cm.task_last_attempt[task_id]
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 301
```

The `301` comes because I submitted `300` tasks. 

This is my script:

```shell
vine_submit_workers -T condor crcfe01 9123 20 &
python cctools/taskvine/src/examples/vine_example_function_call.py

txn_log="vine-run-info/most-recent/vine-logs/transactions"
save_png="vine-run-info/most-recent/vine-logs/txn.png"
vine_plot_txn_log $txn_log $save_png
```

**Comment by JinZhou5042** [comment]
According to the function `_parse_task`, we update `self.cm.task_last_attempt` whenever the `event` of a task is `READY`, and define `la` and `ca` accordingly:

```python
def _parse_task(self, time, manager_pid, task_id, event, arg):
    task_id = int(task_id)

    if not self.check_task_range(task_id):
        return

    if event == "READY":
        (category, allocation, attempt_number, arg) = arg.split()
        self.cm.task_last_attempt[task_id] = attempt_number
    
    la = self.cm.task_last_attempt[task_id]
    ca = self.cm.tasks_attempts[task_id][la]

    ......
```

However, a LIBRARY is a part of TASK, as indicated by `transaction` log information.

This is LIBRARY:

![Screenshot from 2023-11-15 16-12-46](https://github.com/cooperative-computing-lab/cctools/assets/142265839/a82bdb06-dd61-49d7-ac30-bf4220564158)

This is TASK:

<img width="1221" alt="Untitled" src="https://github.com/cooperative-computing-lab/cctools/assets/142265839/a128564a-28ec-4659-b09a-686bcccb45dd">

The bottom tasks numbered 301 and 302 were library tasks and do not have a `READY` event, which triggers an error when accessing the key of dictionary but not defined.

**Comment by JinZhou5042** [comment]
The condition is pretty similar for function `_parse_library`, too.
