### ISSUE TITLE
workqueue: worker disconnections and eventual hang under high load

### ISSUE THREAD

**Issue by benclifford** [cooperative-computing-lab/cctools#3587]
In the same high load environment as #3583  (loadaverage around 700, on a 120 core machine), I have encountered a hang where no further progress is made:

I see several times in the run, the only work_queue_worker disconnects and restarts several times:

```
runinfo/001> cat submit_scripts/parsl.work_queue.block-0.1702300756.4139926.sh.out
Found cores : 256
Launching worker: 1
work_queue_worker: creating workspace /tmp/worker-76945-2231540
work_queue_worker: using 256 cores, 350000 MB memory, 432682 MB disk, 0 gpus
connected to manager nid004382:1024 via local address 10.249.2.72:54684
disconnected from manager nid004382:1024
connected to manager nid004382:1024 via local address 10.249.2.72:58398
disconnected from manager nid004382:1024
connected to manager nid004382:1024 via local address 10.249.2.72:45328
disconnected from manager nid004382:1024
connected to manager nid004382:1024 via local address 10.249.2.72:35760
disconnected from manager nid004382:1024
work_queue_worker: deleting workspace /tmp/worker-76945-2231540
All workers done
```

On the final restart (around 05:35) , no further jobs were run, even though the worker process still existed - I then killed that (around 05:47) and let parsl start up a new work_queue_worker which then finished off all the remaining work.

In the corresponding `.err` file (which contains stderr corresponding to the above stdout), I see a lot of these from parsl_coprocess.py:

```
Traceback (most recent call last):
  File "/pscratch/sd/b/bxc/descprod-out/installs/g3wf-w2348-parsl/bin/parsl_coprocess.py", line 115, in main
    conn.sendall(response)
BrokenPipeError: [Errno 32] Broken pipe
```

In addition that file has a lot of other errors to do with `psutil`, which are expected when parsl process monitoring tries to get info about a process that has gone away - that shouldn't be causing any problems other than generating log messages.

I'm not sure how to debug this further (and I'll be doing stuff to reduce the load average significantly, but I still expect this node to be running at some kind of saturation level...) so I'm dumping what I have into an issue.

[runinfo-001.tar.gz](https://github.com/cooperative-computing-lab/cctools/files/13637613/runinfo-001.tar.gz)

**Comment by dthain** [comment]
Hi Ben thanks for the update.  To clarify: is the WQ worker started by the Parsl provider interface, or something else?

**Comment by benclifford** [comment]
@dthain yes it's started by the parsl local provider, inside the main workflow process, which is inside a slurm job. everything is running on this one single node.

**Comment by dthain** [comment]
Some quick observations to get oriented:
- `work_queue/debug_log` shows the WQ manager starting at 05:18:34 and ending at 05:51:11.
- 191 tasks are submitted right away.
```
2023/12/11 05:19:15.42 work_queue_python[2231452] wq: Task 191 state change: UNKNOWN (0) to WAITING (1)
```
- worker connects right away:
```
2023/12/11 05:20:32.11 work_queue_python[2231452] tcp: accepted connection from 10.249.2.72 port 54684
2023/12/11 05:20:32.11 work_queue_python[2231452] wq: worker 10.249.2.72:54684 connected
2023/12/11 05:20:32.11 work_queue_python[2231452] wq: workers connections -- known: 0, connecting: 0, available: 0.
2023/12/11 05:20:32.11 work_queue_python[2231452] wq: rx from unknown (10.249.2.72:54684): workqueue 11 nid004382 Linux x86_64 7.7.3
2023/12/11 05:20:32.11 work_queue_python[2231452] wq: 1 workers are connected in total now
```
- first task starts running at 05:20:32:
```
2023/12/11 05:20:32.12 work_queue_python[2231452] wq: nid004382 (10.249.2.72:54684) busy on
 'run_parsl_task'
2023/12/11 05:20:32.12 work_queue_python[2231452] wq: Task 92 state change: WAITING (1) to 
RUNNING (2)
2023/12/11 05:20:32.12 work_queue_python[2231452] wq: rx from nid004382 (10.249.2.72:54684): info tasks_running 1
```
- eventually 64 tasks running:
```
2023/12/11 05:20:32.23 work_queue_python[2231452] wq: Task 80 state change: WAITING (1) to 
RUNNING (2)
2023/12/11 05:20:32.23 work_queue_python[2231452] wq: rx from nid004382 (10.249.2.72:54684): info tasks_running 64
```
- task 345 is the last task given to the manager:
```
2023/12/11 05:47:28.32 work_queue_python[2231452] wq: Task 345 state change: UNKNOWN (0) to WAITING (1)
```
- after that, the manager continues to send tasks and retrieve outputs until all tasks are sent.  Then it keeps retrieving complete tasks until all are done:
```
2023/12/11 05:51:11.47 work_queue_python[2231452] wq: Task 294 state change: WAITING_RETRIEVAL (3) to RETRIEVED (4)
2023/12/11 05:51:11.47 work_queue_python[2231452] wq: nid004382 (10.249.2.72:54366) done in 145.17s total tasks 64 average 139.69s
2023/12/11 05:51:11.47 work_queue_python[2231452] wq: Task 294 state change: RETRIEVED (4) to DONE (5)
```

The log ends at that point, but the manager doesn't have any more to do.

**Comment by dthain** [comment]
Here is where the manager-worker connections fail:

The first one is a failure to respond to keep alive:
```
2023/12/11 05:26:26.66 work_queue_python[2231452] wq: workers connections -- known: 1, connecting: 0, available: 
1.
2023/12/11 05:26:32.67 work_queue_python[2231452] wq: tx to nid004382 (10.249.2.72:54684): check
2023/12/11 05:26:32.67 work_queue_python[2231452] wq: Sent keepalive check to worker nid004382 (10.249.2.72:54684
)
2023/12/11 05:27:03.60 work_queue_python[2231452] wq: Removing worker nid004382 (10.249.2.72:54684): hasn't respo
nded to keepalive check for more than 30 s
2023/12/11 05:27:03.60 work_queue_python[2231452] wq: worker nid004382 (10.249.2.72:54684) removed
```
Another one here:
```
2023/12/11 05:27:34.63 work_queue_python[2231452] wq: rx from nid004382 (10.249.2.72:58398): info tasks_running 1
28
2023/12/11 05:27:34.63 work_queue_python[2231452] wq: rx from nid004382 (10.249.2.72:58398): info tasks_running 1
29
2023/12/11 05:29:34.63 work_queue_python[2231452] wq: tx to nid004382 (10.249.2.72:58398): check
2023/12/11 05:29:34.63 work_queue_python[2231452] wq: Sent keepalive check to worker nid004382 (10.249.2.72:58398
)
2023/12/11 05:30:04.67 work_queue_python[2231452] wq: Removing worker nid004382 (10.249.2.72:58398): hasn't responded to keepalive check for more than 30 s
2023/12/11 05:30:04.67 work_queue_python[2231452] wq: worker nid004382 (10.249.2.72:58398) removed
```
This one is a failure to return an output file in a timely way:
```
2023/12/11 05:35:20.11 work_queue_python[2231452] wq: nid004382 (10.249.2.72:45328) sending back file-1211-dca94e
30118b84329f399a16643d98e6-log to /pscratch/sd/b/bxc/descprod-out/jobs/job001402/runinfo/001/work_queue/function_
data/0201/log
2023/12/11 05:35:20.11 work_queue_python[2231452] wq: tx to nid004382 (10.249.2.72:45328): get file-1211-dca94e30
118b84329f399a16643d98e6-log 1
2023/12/11 05:35:25.12 work_queue_python[2231452] wq: 10.249.2.72:45328 (nid004382) failed to return output file-1211-dca94e30118b84329f399a16643d98e6-log to /pscratch/sd/b/bxc/descprod-out/jobs/job001402/runinfo/001/work_queue/function_data/0201/log
2023/12/11 05:35:25.12 work_queue_python[2231452] wq: tx to nid004382 (10.249.2.72:45328): kill 202
2023/12/11 05:35:25.12 work_queue_python[2231452] wq: Failed to receive output from worker nid004382 (10.249.2.72:45328).
2023/12/11 05:35:25.12 work_queue_python[2231452] wq: worker nid004382 (10.249.2.72:45328) removed
```

**Comment by dthain** [comment]
The worker debugging is not turned on, however the stdout of the worker can be found here:

Clearly the functions are executing as desired to begin with:
```
Network function: connection from ('127.0.0.1', 49930)
Network function: recieved event: {'fn_kwargs': {}, 'fn_args': ['map', 'function', 'result', 'log'], 'remote_task
_exec_method': 'direct'}
Network function: connection from ('127.0.0.1', 48776)
Network function: recieved event: {'fn_kwargs': {}, 'fn_args': ['map', 'function', 'result', 'log'], 'remote_task
_exec_method': 'direct'}
Network function: connection from ('127.0.0.1', 43660)
Network function: recieved event: {'fn_kwargs': {}, 'fn_args': ['map', 'function', 'result', 'log'], 'remote_task
_exec_method': 'direct'}
```
And then at some point some monitoring starts failing, due to an inability to open things in `/proc/XXXX`
```
  File "/pscratch/sd/b/bxc/descprod-out/installs/g3wf-w2348-parsl/lib/python3.11/site-packages/psutil/_pslinux.py
", line 1655, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=415258)
ERROR:root:Exception reading IO counters for child num_threads. Recorded IO usage may be incomplete
Traceback (most recent call last):
  File "/pscratch/sd/b/bxc/descprod-out/installs/g3wf-w2348-parsl/lib/python3.11/site-packages/psutil/_pslinux.py", line 1650, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pscratch/sd/b/bxc/descprod-out/installs/g3wf-w2348-parsl/lib/python3.11/site-packages/psutil/_pslinux.py", line 1829, in io_counters
    with open_binary(fname) as f:
         ^^^^^^^^^^^^^^^^^^
  File "/pscratch/sd/b/bxc/descprod-out/installs/g3wf-w2348-parsl/lib/python3.11/site-packages/psutil/_common.py", line 772, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/417624/io'
```

Two things aren't immediately clear to me:
1 - Where is this monitoring code coming from?  Is Parsl attaching a monitor to the function, or is it coming from somewhere else?
2 - Which process is it attempting to monitor?  Clearly the desired process isn't there.  Is there some mixup that results from the monitoring getting passed from parsl -> wq -> worker ?

**Comment by benclifford** [comment]
This bit is parsl code (in a wrapper around the raw parsl task, so from the perspective of parsl_coprocess.py, it is "part of the parsl task") attempting to walk the process tree of processes launched from a particular parsl task.

In this particular user's case they have a lot of their task implemented in fork-heavy bash, so there are a lot of processes (`bc`, `ps`, `date`, that sort of thing) which exist at the point that the parsl monitoring code sees they exist, but then have disappeared by the time that the code gets round to inspecting them.

Those exceptions are "expected" for that reason, and the monitoring code should just skip that iteration and go round again on the next poll.

**Comment by dthain** [comment]
Ok then I think what we need to understand this further is the debug log from the worker. 
If you can arrange to add `-d all` to the command line arguments of the worker, then we
should get the debug output back in the `.err` file coming from the batch system.

**Comment by benclifford** [comment]
ok. I'll add that. My last couple of runs have been (with less load) completed successfully though, so don't expect anything useful too soon.

**Comment by dthain** [comment]
I have a suspicion that there is the potential of deadlock between the worker and the coprocess, but I need to set up some experiments to push at this harder to see if I can reproduce.

**Comment by dthain** [comment]
@benclifford I have found a few boundary cases in WQ coprocess that are fixed in #3600.

Again, this invokes some updates to `wq_network_code.py` which is aliased by `parsl_coprocess.py`
https://github.com/Parsl/parsl/blob/master/parsl/executors/workqueue/parsl_coprocess.py

So we will need to coordinate an update to that file as well when this is released.

@colinthomas-z80 FYI

**Comment by dthain** [comment]
Depends on #3619 

I think we are ready to test this once the new release is made.

**Comment by dthain** [comment]
@benclifford we fixed several issues related to Parsl-WQ in the latest release, please let us know if this is still a problem.

**Comment by dthain** [comment]
@benclifford going back to review stale issues.  Is this still a problem?
