### ISSUE TITLE
Running DV3 into Failures

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3858]
I am still having issues to get DV3 running in `crcfe01`...

The snapshot of error messages
```
task id 743 key ('<dask-awkward.lib.core.ArgsKwargsPackedFunction 
ob-f7d53d129bcb0459db41d664fec3ca5c', 31) failed: success. 0 attempts left.
Traceback (most recent call last):
  File 
"/var/condor/execute/dir_423414/worker-241627-423448/task.743/w_afb73624-d71c-4e85-9ebf-f41
f0feb435c", line 9, in <module>
    args, kwargs = cloudpickle.load(f)
                   ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'coffea.dataset_tools'

tasks ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0/381 -:--:--
Traceback (most recent call last):
  File "/project01/ndcms/jzhou24/2023hggprocessor/dv3_processor.py", line 116, in <module>
    with open(preprocessed_path, "r") as fr:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dataset_runable_preprocessed.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project01/ndcms/jzhou24/2023hggprocessor/dv3_processor.py", line 133, in <module>
    dataset_runable, dataset_updated = preprocess(
                                       ^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/cctools-dev/lib/python3.12/site-packages/coffea/dataset_tools/preprocess.py", line 366, in preprocess
    (all_processed_files,) = dask.compute(files_to_preprocess, scheduler=scheduler)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/cctools-dev/lib/python3.12/site-packages/dask/base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/cctools-dev/lib/python3.12/site-packages/ndcctools/taskvine/dask_executor.py", line 188, in get
    raise e
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/cctools-dev/lib/python3.12/site-packages/ndcctools/taskvine/dask_executor.py", line 185, in get
    return self._dask_execute(dsk, keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/cctools-dev/lib/python3.12/site-packages/ndcctools/taskvine/dask_executor.py", line 285, in _dask_execute
    raise Exception(f"tasks for key {t.key} failed permanently")
Exception: tasks for key ('<dask-awkward.lib.core.ArgsKwargsPackedFunction ob-f7d53d129bcb0459db41d664fec3ca5c', 31) failed permanently
```

The environment I am using
```
name: ndcms
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - atk-1.0=2.36.0=ha1a6a79_0
  - beautifulsoup4=4.12.2=py311h06a4308_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - blas=1.0=mkl
  - bokeh=3.3.4=pyhd8ed1ab_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cffi=1.16.0=py311hb3a22ac_0
  - clang=14.0.6=h06a4308_1
  - clang-14=14.0.6=default_hc6dbbc7_1
  - clang-format=17.0.6=default_hb11cfb5_2
  - clang-format-17=17.0.6=default_hb11cfb5_2
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - conda-pack=0.7.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h9547e67_0
  - cytoolz=0.12.3=py311h459d7ec_0
  - dask-jobqueue=0.8.5=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2023.12.2=pyhca7485f_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.72.0=py311hbb6d50b_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libclang-cpp14=14.0.6=default_hc6dbbc7_1
  - libclang-cpp17=17.0.6=default_hb11cfb5_2
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgd=2.3.3=h695aa2c_1
  - libglib=2.78.4=hdc74915_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libllvm17=17.0.6=hc9c083f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenssl-static=3.2.0=hd590300_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - librsvg=2.54.4=h36cc946_3
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_4
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.4=hf1b16e4_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.7=py311h9547e67_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.0=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - pango=1.50.7=h05da053_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py311h5eee18b_0
  - pip=23.3.1=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.7=h955ad1f_0
  - python-graphviz=0.20.1=py311h06a4308_0
  - python_abi=3.11=2_cp311
  - pytorch=2.1.0=cpu_py311h6d93b4c_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - swig=4.0.2=h295c915_4
  - sympy=1.12=pyh04b8f61_3
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.4=py311h459d7ec_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - wheel=0.41.2=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - awkward==2.4.10
      - awkward-cpp==25
      - boost-histogram==1.4.0
      - cachetools==5.3.2
      - coffea==2023.10.0rc1
      - correctionlib==2.4.0
      - cycler==0.12.1
      - dask==2024.1.0
      - dask-awkward==2023.11.2
      - dask-histogram==2023.10.0
      - distributed==2024.1.0
      - fastjet==3.4.1.3
      - flake8==7.0.0
      - fonttools==4.47.2
      - hist==2.7.2
      - histoprint==2.4.0
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - lz4==4.3.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mplhep==0.3.31
      - mplhep-data==0.0.3
      - numba==0.58.1
      - numpy==1.25.2
      - pandas==2.1.4
      - psutil==5.9.7
      - pyarrow==14.0.2
      - pycodestyle==2.11.1
      - pydantic==1.10.13
      - pyflakes==3.2.0
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - rich==13.7.0
      - scipy==1.11.4
      - toml==0.10.2
      - toolz==0.12.0
      - tqdm==4.66.1
      - tzdata==2023.4
      - uhi==0.4.0
      - uproot==5.2.1
      - urllib3==2.1.0
      - vector==1.1.1.post1
prefix: /afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/ndcms
```

I zipped this environment and generated `ndcms.tar.gz` via
```
poncho_package_create $CONDA_PREFIX ndcms.tar.gz
```

The way I launched workers is
```
vine_factory -T condor -C factory.json  --scratch-dir /scratch365/jzhou24/ --python-env=ndcms.tar.gz
```
and the `factory.json`
```
{
    "manager-name": "jzhou24-hgg",
    "max-workers": 4,
    "min-workers": 4,
    "workers-per-cycle": 4,
    "cores": 16,
    "memory": 20000,
    "disk": 50000,
    "timeout": 36000
}
```

Did I miss something there...

**Comment by btovar** [comment]
The tasks didn't execute inside a worker with the correct environment? One possibility is that you have workers active that launched previously without the correct environment.

**Comment by btovar** [comment]
Sorry, I meant to close another issue.

**Comment by JinZhou5042** [comment]
I modified the project name so that the manager and new workers can pair, but still have the same problem... Maybe I missed some important packages, or installed a couple of packages with incorrect versions...

**Comment by dthain** [comment]
As a general rule, focus on the first errors encountered, since they may cascade into others.

These seem like the most essential problems right up front.
```
ModuleNotFoundError: No module named 'coffea.dataset_tools'
FileNotFoundError: [Errno 2] No such file or directory: 'dataset_runable_preprocessed.json'
```

@cmoore24-24 can you give us a hand here?

**Comment by btovar** [comment]
coffea.dataset_tools should have been installed together with coffea. I'd start with a new environment, remove ndcms.tar.gz and repack it again.

**Comment by cmoore24-24** [comment]
I agree with Ben-- dataset_tools should have been included with core coffea. The missing json file, I'm less sure about.

**Comment by JinZhou5042** [comment]
I started a new environment and reinstalled everything, it's now running quite well...
