### ISSUE TITLE
vine: task fails due to resource exhaustion

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3934]
I got these error messages while running Connor's latest DV5:
```
task id 11776 key ('particleNetMD-QCD-5804a733bde556f20aaceff1fc416374', 34) failed: 
resource exhaustion. 4 attempts left.

task id 11777 key ('color-ring-6c5d7dd1c7f2c8c99e7e6d8ae2b194eb', 34) failed: resource 
exhaustion. 4 attempts left.

task id 11778 key ('msoftdrop-2b80e8d5da0b757868d77771ef949cd5', 34) failed: resource 
exhaustion. 4 attempts left.

task id 11849 key ('msoftdrop-2b80e8d5da0b757868d77771ef949cd5', 124) failed: resource exhaustion. 4 
attempts left.

task id 11865 key ('color-ring-6c5d7dd1c7f2c8c99e7e6d8ae2b194eb', 40) failed: resource exhaustion. 4 
attempts left.

......

Traceback (most recent call last):
  File "/project01/ndcms/jzhou24/hgg/notebooks/skims/skimmer/ecf_calculator.py", line 375, in <module>
    computed = dask.compute(
               ^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/coffea2024.4.0/lib/python3.11/site-packages/dask/base.py", line 662, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/coffea2024.4.0/lib/python3.11/site-packages/ndcctools/taskvine/dask_executor.py", line 192, in get
    raise e
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/coffea2024.4.0/lib/python3.11/site-packages/ndcctools/taskvine/dask_executor.py", line 189, in get
    return self._dask_execute(dsk, keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/j/jzhou24/miniconda3/envs/coffea2024.4.0/lib/python3.11/site-packages/ndcctools/taskvine/dask_executor.py", line 290, in _dask_execute
    raise Exception(f"tasks for key {t.key} failed permanently")
Exception: tasks for key ('particleNetMD-QCD-5804a733bde556f20aaceff1fc416374', 289) failed permanently
```

I don't know is it because I didn't configure the resources very well or some disk allocation problems in TaskVine. [logs](https://drive.google.com/file/d/1W7Nk2G9jrBRjHx2a4hRvcr_bfO7AZJV-/view?usp=drive_link) are here.

For example, for task 11776, these are the resources allocated to it:
```
2024/09/16 14:36:01.88 vine_manager[2686687] vine: tx to d32cepyc023.crc.nd.edu (10.32.89.165:54664): cores 1.000
2024/09/16 14:36:01.88 vine_manager[2686687] vine: tx to d32cepyc023.crc.nd.edu (10.32.89.165:54664): gpus 0
2024/09/16 14:36:01.88 vine_manager[2686687] vine: tx to d32cepyc023.crc.nd.edu (10.32.89.165:54664): memory 10009
2024/09/16 14:36:01.88 vine_manager[2686687] vine: tx to d32cepyc023.crc.nd.edu (10.32.89.165:54664): disk 1
```
The disk amount is only 1, which looks so strange to me.

The factory.json

```
{
    "manager-name": "jzhou24-hgg2",
    "max-workers": 200,
    "min-workers": 60,
    "workers-per-cycle": 60,
    "cores": 4,
    "memory": 100000,
    "disk": 100000,
    "timeout": 36000
}
```

The command to launch factory
```
vine_factory -T condor -C factory.json --scratch-dir /scratch365/jzhou24/vine_scratch --python-env ndcms.tar.gz
```

**Comment by btovar** [comment]
Fixed with #3935
