### ISSUE TITLE
vine: non-temporary files lost permanently because of worker crashes

### ISSUE THREAD

**Issue by JinZhou5042** [cooperative-computing-lab/cctools#3993]
We ran into an input missing error with the latest source-built cctools, this is the original terminal output:

```
(coffea2) [cmoore24@glados skimmer]$ python jet_processor.py 
/afs/crc.nd.edu/user/c/cmoore24/Public/hgg/notebooks/skims/skimmer/variable_functions.py:3: FutureWarning: In version 2024.7.0 (target date: 2024-06-30 11:59:59-05:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  import coffea.nanoevents.methods.vector as vector
qcd_1000to1400
qcd_1400to1800
qcd_1800to2400
qcd_2400to3200
qcd_300to470
qcd_3200toInf
qcd_470to600
qcd_600to800
qcd_800to1000
start compute
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38776/317955 23:21:472024/11/25 16:43:16.29 vine_manager[564484] notice: input file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 couldn't be accessed: No such file or directory
task id 79530 key ('PFCands-02852c02f9921fe7a80de1cd2057902c', 3652) failed: 
input missing. 4 attempts left.
None
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38778/317955 22:59:452024/11/25 16:43:16.38 vine_manager[564484] notice: input file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 couldn't be accessed: No such file or directory
task id 80086 key ('PFCands-02852c02f9921fe7a80de1cd2057902c', 3652) failed: 
input missing. 3 attempts left.
None
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38778/317955 22:59:452024/11/25 16:43:16.53 vine_manager[564484] notice: input file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 couldn't be accessed: No such file or directory
task id 80087 key ('PFCands-02852c02f9921fe7a80de1cd2057902c', 3652) failed: 
input missing. 2 attempts left.
None
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38802/317955 20:41:042024/11/25 16:43:20.12 vine_manager[564484] notice: input file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 couldn't be accessed: No such file or directory
task id 79529 key ('FatJetPFCands-2c9c8ab328aab8dc871be8fefdee9092', 3652) 
failed: input missing. 4 attempts left.
None
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38805/317955 20:26:572024/11/25 16:43:20.55 vine_manager[564484] notice: input file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 couldn't be accessed: No such file or directory
task id 80088 key ('PFCands-02852c02f9921fe7a80de1cd2057902c', 3652) failed: 
input missing. 1 attempts left.
None
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38829/317955 18:16:062024/11/25 16:43:23.84 vine_manager[564484] notice: input file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 couldn't be accessed: No such file or directory
task id 80110 key ('PFCands-02852c02f9921fe7a80de1cd2057902c', 3652) failed: 
input missing. 0 attempts left.
None
tasks ━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  38832/317955 18:10:25
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/c/cmoore24/Public/hgg/notebooks/skims/skimmer/jet_processor.py", line 367, in <module>
    computed = dask.compute(
               ^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/c/cmoore24/miniconda3/envs/coffea2/lib/python3.11/site-packages/dask/base.py", line 660, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/c/cmoore24/miniconda3/envs/coffea2/lib/python3.11/site-packages/ndcctools/taskvine/dask_executor.py", line 196, in get
    raise e
  File "/afs/crc.nd.edu/user/c/cmoore24/miniconda3/envs/coffea2/lib/python3.11/site-packages/ndcctools/taskvine/dask_executor.py", line 193, in get
    return self._dask_execute(dsk, keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/crc.nd.edu/user/c/cmoore24/miniconda3/envs/coffea2/lib/python3.11/site-packages/ndcctools/taskvine/dask_executor.py", line 294, in _dask_execute
    raise Exception(f"tasks for key {t.key} failed permanently")
Exception: tasks for key ('PFCands-02852c02f9921fe7a80de1cd2057902c', 3652) failed permanently
```

It says that one some tasks failed permanently because their inputs were missing in the manager's **staging directory**. That said, those files are not temporary files, but regular vine files. It makes me wonder if there is a code brooming staging files while executing, and this is how the log says (I attached line ids at the frontier of each line):

```
1  | 2024/11/25 16:42:09.19 vine_manager[564484] vine: rx from qa-xp-018.crc.nd.edu (10.32.88.131:41488): file file-rnd-rvjcpbkuacribkr 24823159 0644 1732570928
2  | 2024/11/25 16:42:09.19 vine_manager[564484] vine: qa-xp-018.crc.nd.edu (10.32.88.131:41488) using worker's observed average transfer rate of 75.76 MB/s
3  | 2024/11/25 16:42:09.19 vine_manager[564484] vine: qa-xp-018.crc.nd.edu (10.32.88.131:41488) will try up to 60 seconds to transfer this 24.82 MB file.
4  | 2024/11/25 16:42:09.20 vine_manager[564484] vine: Receiving file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3 (size: 24823159 bytes) from 10.32.88.131:41488 (qa-xp-018.crc.nd.edu) ...
5  | 2024/11/25 16:42:09.31 vine_manager[564484] vine: Received item size (10164960) does not match the expected size - 24823159 bytes.
6  | 2024/11/25 16:42:09.32 vine_manager[564484] vine: 10.32.88.131:41488 (qa-xp-018.crc.nd.edu) failed to return output file-rnd-rvjcpbkuacribkr to /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/outputs/dd9b7515-ebf5-4d19-b556-315d961653f3
7  | 2024/11/25 16:42:09.32 vine_manager[564484] vine: tx to qa-xp-018.crc.nd.edu (10.32.88.131:41488): unlink file-meta-df0818a612aa23cf9ba779bad884d938
8  | 2024/11/25 16:42:09.32 vine_manager[564484] vine: Task 17922 state change: WAITING_RETRIEVAL (3) to RETRIEVED (4)
9  | 2024/11/25 16:42:09.32 vine_manager[564484] vine: tx to qa-xp-018.crc.nd.edu (10.32.88.131:41488): kill 17922
10 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: qa-xp-018.crc.nd.edu (10.32.88.131:41488) done in 7.55s total tasks 12 average 7.71s
11 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: task 1115 has a ready transfer source for all files
12 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: qa-xp-018.crc.nd.edu (10.32.88.131:41488) needs file /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/arguments/9ba030ff-a17d-4f1f-969d-815d5c446638 as a_9ba030ff-a17d-4f1f-969d-815d5c446638
13 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: tx to qa-xp-018.crc.nd.edu (10.32.88.131:41488): put file-meta-4505bcef52d537fd2d5dd0f0a94e2e8e 0 482161
14 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: tx to qa-xp-018.crc.nd.edu (10.32.88.131:41488): file file-meta-4505bcef52d537fd2d5dd0f0a94e2e8e 482161 0644 1732566476
15 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: qa-xp-018.crc.nd.edu (10.32.88.131:41488) failed to send /project01/ndcms/cmoore24/vine-run-info/2024-11-25T152602/staging/arguments/9ba030ff-a17d-4f1f-969d-815d5c446638 (-1 bytes sent).
16 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: Task 1115 state change: READY (1) to RUNNING (2)
17 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: Failed to send task 1115 to worker qa-xp-018.crc.nd.edu (10.32.88.131:41488).
18 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: worker qa-xp-018.crc.nd.edu (10.32.88.131:41488) removed
19 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: Recalling worker qa-xp-018.crc.nd.edu's temp files
20 | 2024/11/25 16:42:09.32 vine_manager[564484] vine: Removing instances of worker from transfer table
```

Line `1-4` says that an output file is produced on a worker and the manager tries to receive it to its own staging directory.
`5-6` says that only half sized file is retrieved, I looked at both the worker and the manager's disk usage and found that they were just sufficient. So that probably indicates a worker crash while transferring files.
`7-10` sets the state of the task with output transferring failed to `RETRIEVED`, which is potentially problematic.
`11-14` the manager tries to send more tasks to the crashed worker
`15-20` it finally knows that the worker had been crashed and opts to remove it

The lost file has a cache name (on the worker) `file-rnd-rvjcpbkuacribkr` and has a staging name `dd9b7515-ebf5-4d19-b556-315d961653f3` on the manager. Because the transfer failed, file `dd9b7515-ebf5-4d19-b556-315d961653f3` doesn't exist on the manager and all children tasks will fail with input missing errors.

Though I am not sure if this issue is related to a specific version of cctools, did I miss something there?

Tagging @cmoore24-24 as this came from a run in DV5.

**Comment by dthain** [comment]
Ah, this is a subtle one but I think I can help you out here.

Our general rule is this:
1 - A failure to *transfer* a file indicates that the task is not complete and should be put back in the queue and retried.
2 - However, if the manager asks the worker for an output files and it *does not exist*, then the task should be given back to the user, so the user can troubleshoot why the task didn't behave as expected.

The manager is failing to transfer the file, so this should be a type 1 error.  Instead, it should be a type 2 error.

Look around in the vicinity here to see what's going wrong:
https://github.com/cooperative-computing-lab/cctools/blob/8530039e2e7560b6a2a93e9468b552ecce343e9e/taskvine/src/manager/vine_manager_get.c#L373

**Comment by cmoore24-24** [comment]
Just to add my two cents of user experience here, my encountering this issue does depend on the version of cctools I use. Anecdotally, if I use version 7.13.3 or later (i.e. if I build from source) I run into this pretty much without exception on my at-scale runs. 7.13.2 and lower appear to be safe. I was able to successfully  complete the run that produced the above error on 7.13.2, to be precise.
