### ISSUE TITLE
voms-proxy-init reports that 'ls -al <PATH>' fails under parrot/cvmfs

### ISSUE THREAD

**Issue by jblomer** [cooperative-computing-lab/cctools#927]
Hi all,

following #919 and #921 we hit another block with the `voms-proxy-init` command.  In order to reproduce the steps, you can create a throw-away certificate and key with

    openssl req -x509 -newkey rsa:2048 -keyout /tmp/userkey.pem -out /tmp/usercert.pem -days 10 -nodes -subj "/"

With this in place, the following two steps under fuse-mounted cvmfs result in the expected error 'User credential is not valid!'.

    source /cvmfs/grid.cern.ch/emi3ui-latest/etc/profile.d/setup-ui-example.sh
    voms-proxy-init -voms cms -cert /tmp/usercert.pem -key /tmp/userkey.pem -debug

If ran under parrot, the error is 

    Credentials couldn't be loaded [/tmp/userkey.pem, /tmp/usercert.pem]: Cannot list properties for file '/tmp/userkey.pem': error invoking the 'ls -al /tmp/userkey.pem' os command!
    No credentials found!

I tried to create a debug log.  If the debug log is redirected to a file, the problem does not occur.  Perhaps this could be a hint to the cause of the issue.

Thanks for any help,
Jakob

**Comment by btovar** [comment]
Jakob,

Is this inside the docker container?

**Comment by jblomer** [comment]
It's both within and without the docker container.

**Comment by jblomer** [comment]
I forgot, the mode of the key and the certificate in /tmp should be changed to 0400.

**Comment by btovar** [comment]
With parrot_run bash, I do see a:

2015/09/23 07:57:20.85 parrot_run[29017] <child:29037> syscall: mprotect
2015/09/23 07:57:20.85 parrot_run[29017] <child:29028> syscall: = 1 [futex]
2015/09/23 07:57:20.85 parrot_run[29017] <child:29037> syscall: = 0 [mprotect]
2015/09/23 07:57:20.85 parrot_run[29017] process: pid 29028 received signal 11 (Segmentation fault) (state 1)
2015/09/23 07:57:20.85 parrot_run[29017] process: pid 29028 faulted on address 0x7f9e162fb880 (permissions)

**Comment by btovar** [comment]
If ran again:
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> debug: allocated channel `(null)':30000:4096
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> debug: divert_to_channel(29480, pread64, 0x7f935e215090, 280, 196608)
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> debug: --> pread64(5, 0x7f935e215090, 280, 196608)
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> debug: channel read 280
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> debug: decreasing refcount to 0 for channel `(null)':30000:4096
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> debug: freeing channel `(null)':30000:4096
2015/09/23 08:04:29.56 parrot_run[29468] <child:29480> syscall: = 280 [read]
2015/09/23 08:04:29.56 parrot_run[29468] process: pid 29480 received signal 11 (Segmentation fault) (state 1)
2015/09/23 08:04:29.56 parrot_run[29468] process: pid 29480 faulted on address 0x8 (unmapped)

@batrick?

**Comment by btovar** [comment]
@batrick, I see this after 0e3a63d5d391eb941f351d9706856fe3fc1e070c.

**Comment by btovar** [comment]
Unlike @jblomer, I am able to redirect to a log file with the problem showing up.

**Comment by batrick** [comment]
The segmentation fault is a red herring. voms-proxy-init segfaults under fuse too.

**Comment by batrick** [comment]
@jblomer, I have tried reproducing this in two environments. The first one it works expected:

With the `hepsw/cvmfs-base` docker image on kernel `4.1.6-1-ARCH`.  I get this expected result:

````
Looking for user credentials in [userkey.pem, usercert.pem]...
Credentials loaded successfully [userkey.pem, usercert.pem]
Certificate validation error: No trusted CA certificate was found for the certificate chain
Certificate validation error: Trusted issuer of this certificate was not established
User credential is not valid!
org.italiangrid.voms.VOMSError: User credential is not valid!
        at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.validateUserCredential(DefaultVOMSProxyInitBehaviour.java:152)
        at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.initProxy(DefaultVOMSProxyInitBehaviour.java:190)
        at org.italiangrid.voms.clients.VomsProxyInit.execute(VomsProxyInit.java:307)
        at org.italiangrid.voms.clients.VomsProxyInit.<init>(VomsProxyInit.java:72)
        at org.italiangrid.voms.clients.VomsProxyInit.main(VomsProxyInit.java:56)
````

It's possible the newer kernel version fixes the problem.

On a different machine running RHEL 6.6 using kernel `2.6.32-504.16.2.el6.x86_64`, I get an infinite loop of `sched_yield` system calls:

````
2015/09/23 11:13:08.78 parrot_run[31271] <child:31295> syscall: sched_yield
2015/09/23 11:13:08.78 parrot_run[31271] <child:31294> syscall: sched_yield
2015/09/23 11:13:08.78 parrot_run[31271] <child:31295> syscall: = 0 [sched_yield]
2015/09/23 11:13:08.78 parrot_run[31271] <child:31294> syscall: = 0 [sched_yield]
2015/09/23 11:13:08.78 parrot_run[31271] <child:31293> syscall: = 0 [sched_yield]
2015/09/23 11:13:08.78 parrot_run[31271] <child:31292> syscall: sched_yield
2015/09/23 11:13:08.78 parrot_run[31271] <child:31295> syscall: sched_yield
2015/09/23 11:13:08.78 parrot_run[31271] <child:31294> syscall: sched_yield
2015/09/23 11:13:08.78 parrot_run[31271] <child:31295> syscall: = 0 [sched_yield]
2015/09/23 11:13:08.78 parrot_run[31271] <child:31294> syscall: = 0 [sched_yield]
````

We've seen similar problems with Java in #43 and #505. I don't think we ever figured those bugs out. [Probably, this is just an unrelated problem caused by the older ptrace code in the kernel.]

Can you tell us more about your specific environment?

**Comment by jblomer** [comment]
I tried this on a CernVM (kernel 3.18).  Let me try this on VMs with different kernels, it might take a day or so.

**Comment by batrick** [comment]
@jblomer: FYI, with #929, the RHEL 6.6 machine also gets the correct answer "User credential is not valid!".

**Comment by btovar** [comment]
@jblomer, cctools version 5.2.1 8cd7eadd108699220dec0e23792a491e5d79af0e, has these changes.

**Comment by tommasoboccali** [comment]
probably already outdated, but I tried to take the master of everything and run outside of docker

so simply

 ./parrot_run  --proxy=127.0.0.1:3128  --cvmfs-repo-switching -M/etc/localtime=/cvmfs/cernvm-prod.cern.ch/cvm3/usr/share/zoneinfo/posix/GMT /bin/bash

after which I issue a 

source /cvmfs/grid.cern.ch/emi3ui-latest/etc/profile.d/setup-ui-example.sh 
voms-proxy-init -voms cms

so No 'ls' from CVMFS, using the standard local /bin/* /usr/bin/* for the system executables, including l's'
It crashes with 

Credentials couldn't be loaded [/root/.globus/userkey.pem, /root/.globus/usercert.pem]: Cannot list properties for file '/root/.globus/userkey.pem': error invoking the 'ls -al /root/.globus/userkey.pem' os command!

if run as the previous command.
If I add ' -dall -odebonlyparrot ' it instead works

**Comment by batrick** [comment]
@tommasoboccali I still can't reproduce it using the command you give. However, you said that if you redirect to a file, the problem goes away. Does it happen if you save debug output to stderr (the normal case)? A debug log may help me see the problem without reproducing it.

e.g.

````
./parrot_run --debug=all --proxy=127.0.0.1:3128 --cvmfs-repo-switching -M/etc/localtime=/cvmfs/cernvm-prod.cern.ch/cvm3/usr/share/zoneinfo/posix/GMT /bin/bash 2> parrot.debug
````

**Comment by tommasoboccali** [comment]
ok, it seems to have worked.

On STDOUT it printed
...
Loaded vomses information 'VOMSServerInfo [alias=biomed, voName=biomed, URL=voms://cclcgvomsli01.in2p3.fr:15000, vomsServerDN=/O=GRID-FR/C=FR/O=CNRS/OU=CC-IN2P3/CN=cclcgvomsli01.in2p3.fr]' from /cvmfs/grid.cern.ch/etc/grid-security/vomses.
Looking for user credentials in [/root/.globus/userkey.pem, /root/.globus/usercert.pem]...
Credentials couldn't be loaded [/root/.globus/userkey.pem, /root/.globus/usercert.pem]: Cannot list properties for file '/root/.globus/userkey.pem': error invoking the 'ls -al /root/.globus/userkey.pem' os command!
Looking for user credentials in [/root/.globus/usercred.p12]...
Credentials couldn't be loaded [/root/.globus/usercred.p12]: /root/.globus/usercred.p12 (cannot read file)

(the real problem is the first, error invoking the 'ls, the second is a fallback attempt which is ok to fail: the file is not there)

here is the stderr



thanks!

tom

**Comment by tommasoboccali** [comment]
ok, wrong paste, sorry !

https://www.dropbox.com/s/69sr7uin0rbz8ma/parrot.debug.gz?dl=0

**Comment by batrick** [comment]
So it seems the problem is that the application is trying to `dup2` an fd to one of the "special" file descriptors (3 and 4 in this case), which always fails. Here's the relevant bits of the log:

````
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(79, 140722992840736, 140724267909152)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 79
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 79
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: dup2
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: dup2(78, 0, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 0
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [dup2]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(78, 0, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 78
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 78
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(80, 0, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 80
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 80
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: dup2
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: dup2(81, 1, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 1
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 1 [dup2]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(81, 1, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 81
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 81
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(82, 1, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 82
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 82
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: dup2
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: dup2(83, 2, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: closing parrot fd 2
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 2 [dup2]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(83, 2, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 83
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 83
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(84, 2, 0)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 84
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 84
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: dup2
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = -5 Input/output error [dup2]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(85, 3, 5)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 85
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 85
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 4
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = -1 Bad file descriptor [pfs_close]
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> syscall: = -9 Bad file descriptor [close]
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> libcall: close 5
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: closing parrot fd 5
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> syscall: open
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> libcall: open /proc/self/fd 591872 0
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `0':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `1':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `2':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `6':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `7':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `8':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `9':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `10':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `11':10
....
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `73':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `74':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `75':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `76':10
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> debug: append dirent `77':10
...
2015/09/24 21:40:33.26 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: close 77
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: closing parrot fd 77
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: getdents
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: fdreaddir 5
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: = null
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: = 0 [getdents]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: close 5
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: closing parrot fd 5
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: fcntl
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: fcntl 3 2 0x1
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: = -1 Bad file descriptor [pfs_fcntl]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: = -9 Bad file descriptor [fcntl]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: write
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: allocated channel `(null)':17000:4096
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: divert_to_channel(25486, pwrite64, 0x7ffce87f64bc, 4, 94208)
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: --> pwrite64(3, 0x7ffce87f64bc, 4, 94208)
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: channel wrote 4
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: write 3 0x7f01d01e9000 4
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: = -1 Bad file descriptor [pfs_write]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: write returned -1 instead of 4
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: decreasing refcount to 0 for channel `(null)':17000:4096
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> debug: freeing channel `(null)':17000:4096
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: = -9 Bad file descriptor [write]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: close 3
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> libcall: = -1 Bad file descriptor [pfs_close]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: = -9 Bad file descriptor [close]
2015/09/24 21:40:33.27 parrot_run[25399] <child:25486> syscall: exit_group
2015/09/24 21:40:33.27 parrot_run[25399] debug: pid 25486 received PTRACE_EVENT_EXIT
2015/09/24 21:40:33.27 parrot_run[25399] process: pid 25486 exited normally with code 255
2015/09/24 21:40:33.27 parrot_run[25399] pstree: 25486 exit status 255 (95 syscalls)
2015/09/24 21:40:33.28 parrot_run[25399] <child:25485> syscall: = 25486 [wait4]
````

Specifically, this bit:

````
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: dup2
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = -5 Input/output error [dup2]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: fallthrough close(85, 3, 5)
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 85
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> debug: marking closed native fd 85
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = 0 [pfs_close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: = 0 [close]
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> syscall: close
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: close 4
2015/09/24 21:40:33.20 parrot_run[25399] <child:25486> libcall: = -1 Bad file descriptor [pfs_close]
2015/09/24 21:40:33.21 parrot_run[25399] <child:25486> syscall: = -9 Bad file descriptor [close]
````

This is pretty unfortunate... We're not reserving any of the special file descriptors (0, 1, 2) but the application is insisting on using fd 3 for whatever reason.

Fixing this is problematic. We can move the special file descriptors somewhere else (like 100, 101) but we may see the problem again elsewhere. I will think about this...

**Comment by dthain** [comment]
Let's talk about this one on Friday morning.

**Comment by batrick** [comment]
@jblomer @tommasoboccali, can you give PR #937 a try?

**Comment by tommasoboccali** [comment]
As far as I can see you made it :)
I could test just via parrot, but I get a nice

Your proxy is valid until Sat Sep 26 10:06:28 CEST 2015

at the end

thanks a lot!

tom

**Comment by batrick** [comment]
Hooray! Thanks for testing @tommasoboccali!

**Comment by dthain** [comment]
Nice work @batrick
